#server:
#  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456

  jpa:
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 100
        temp:
          use_jdbc_metadata_defaults: false
    open-in-view: true
    show-sql: true

